### ISSUE TITLE
Works for a day after reboot and then stops working : aiopulse.errors.NotConnectedException

### ISSUE THREAD

**Issue by andrewD-github** [atmurray/aiopulse#18]
Hi, I installed 0.4.6 a few months back and it resolved my issues and was working reliably.

Unfortunately, since updating recently to HA Core 2024.11.1, the issues is back - it only works for a day and then I get the following errors.
(same symptoms as this closed issue https://github.com/atmurray/aiopulse/issues/13 ) 

Thankyou and please let me know if you need more information.

`2024-11-10 20:31:59.538 DEBUG (MainThread) [aiopulse.hub] Sending buffer b'000000032d00009005536d6172745f4964315f793a1b0022018c00000000000000010106006adab22a00010301010010ffec'
2024-11-10 20:31:59.538 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139946383405648] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/acmeda/cover.py", line 106, in async_open_cover
    await self.roller.move_up()
  File "/usr/local/lib/python3.12/site-packages/aiopulse/roller.py", line 104, in move_up
    await self.hub.send_payload(const.COMMAND_MOVE, bytes.fromhex("2201"), message)
  File "/usr/local/lib/python3.12/site-packages/aiopulse/hub.py", line 652, in send_payload
    self.protocol.send(buffer)
  File "/usr/local/lib/python3.12/site-packages/aiopulse/transport.py", line 161, in send
    raise NotConnectedException
aiopulse.errors.NotConnectedException`

**Comment by andrewD-github** [comment]
FYI - I have aiopulse running from config/custom_components/ so I can better debug this. I have added some code to aiopulse/hub.py to disconnect/reconnect on error. Lets see what happens next.

Also, I noticed something important. there is no reload code in "acmeda/__init__.py".
Nothing happens when you reload the integration from the UI. I added the following code and now it reloads as expected.
![image](https://github.com/user-attachments/assets/8cdd8f26-235f-4dcc-830b-1704c9763b5a)

```
async def async_reload_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload config entry."""
    await async_unload_entry(hass, entry)
    await async_setup_entry(hass, entry)
```

**Comment by gavintweedie** [comment]
I've been having this too, new install however. So far I've eliminated DHCP timeouts (set long lease), WIFI dropping out (placed next to AP, on 2.4ghz only), allowing the hub to talk to the cloud, and also tried blocking it phoning home - same issue.

I've found the reliable way to reconnect/rediscover the hub is to:
1. remove the hacs addon
2. reinstall the hacs addon
3. restart homeassistant

Straight away the hub returns as visible. Sometimes just restarting home assistant will do it too. I agree having the reload option that @andrewD-github has added would help troubleshoot.

I'm currently capturing a pcap and waiting for it to next drop to see if that shows any trigger. Will upload/update this ticket if it does reveal anything interesting.

I noticed over in Hubitat the Acmeda code previously had issues with telnet disconnection, so code was added to spot the disconnect and reconnect, see https://community.hubitat.com/t/beta-rollease-acmeda-automate-pulse/37094/4 and https://github.com/Yoonoo/Hubitat/blob/master/Rollease%20Acmeda/Rollease%20Acmeda%20Hub.groovy

I wonder if the fix is as simple as identifying the dropped telnet and restarting it?

**Comment by andrewD-github** [comment]
@gavintweedie My "hacky" solution seems to be working well.
I'll post the code here tomorrow....family movie night is calling me :)

**Comment by gavintweedie** [comment]
Great! I've had a tcpdump running for days now, and it hasn't dropped out. It knows I'm watching :)

**Comment by andrewD-github** [comment]
@gavintweedie My "hacky" solution seems to be working well.
I'll post the code here tomorrow....family movie night is calling me :) 
Edit - code attached. 

Apart from a load of debug messages (will show in red as errors  in log - but that was just so i could see them), the main change is
1) acmeda/init.py added reload code so it now reloads when called
2) aiopuse/hub.py "send_payload"  updated to try a re-connect with retries and a delay.

```
    async def send_payload(self, command, message_type, message, max_retries=3, retry_delay=5):
<snip>
        for attempt in range(1, max_retries + 1):
            try:
                self.protocol.send(buffer)
                return  # Successfully sent
            except errors.NotConnectedException as e:
                _LOGGER.warning(f"{self.host}: Connection lost. Retrying... (Attempt {attempt})")
                await asyncio.sleep(retry_delay)
                await self.reconnect()
            except Exception as e:
                _LOGGER.error(f"{self.host}: Unexpected error while sending payload: {e}")
                raise e

        _LOGGER.error(f"{self.host}: Failed to send payload after {max_retries} attempts.")
        raise errors.NotConnectedException

     async def reconnect(self):
        _LOGGER.info(f"{self.host}: Attempting to reconnect...")
        try:
            await self.disconnect()
            await self.connect()
            _LOGGER.info(f"{self.host}: Reconnected successfully.")
        except Exception as e:
            _LOGGER.error(f"{self.host}: Reconnection failed: {e}")
```
Here you go. No warranty on this one :) Perhaps you can modify the code to narrow down the reason for disconnects.

Put these into custom components and add the custom integration to your devices. (You'll need to remove the existing integration). 
![image](https://github.com/user-attachments/assets/b7bb1e7a-0685-4f86-9e76-d4f9cd91eea6)

[acmeda_aiopulse.zip](https://github.com/user-attachments/files/18375837/acmeda_aiopulse.zip)

**Comment by gavintweedie** [comment]
Thanks, will give it a shot

**Comment by andrewD-github** [comment]
@gavintweedie how did it go ?

**Comment by gavintweedie** [comment]
Been busy this week, next week I'll report back

**Comment by gavintweedie** [comment]
@andrewD-github switched to your modified code today, will give it a few days and try and "encourage" some disconnects and see how well it recovers and report back.

**Comment by gavintweedie** [comment]
Been over a week and haven't been able to get it to disconnect and get stuck disconnected. Your patch seems to do the job and certainly hasn't made anything worse in any way.

I wonder if @atmurray would consider taking it as a patch?

**Comment by gavintweedie** [comment]
I decided to try rebooting the hub to see what happens with the patch, this was a hard power cycle. I found it would not re-connect without reloading the addon.

Only relevant logs I could find. Interestingly the disconnect "not connected" only happens on reload trigger. I think if we could get it to do a keepalive check (send a packet that does nothing? reads blind current position maybe?) and if it doesn't get a reply consider it disconnected, then attempt a reload (with some retry timers/backoff) would solve for this.

10:41 I hit the reload button. Nothing logged before, even trying to send commands like shade up/down didn't result in any errors.

`2025-02-04 10:41:27.355 WARNING (MainThread) [custom_components.aiopulse.transport] 192.168.88.60: Not connected
2025-02-04 10:41:27.356 DEBUG (MainThread) [custom_components.acmeda] Hub setup complete
2025-02-04 10:41:29.078 DEBUG (MainThread) [custom_components.acmeda] Hub info updated
2025-02-04 10:41:29.385 DEBUG (MainThread) [custom_components.acmeda] Hub rooms updated
2025-02-04 10:41:29.484 DEBUG (MainThread) [custom_components.acmeda] Hub rollers updated
2025-02-04 10:41:29.484 DEBUG (MainThread) [custom_components.acmeda] Looking for new AcmedaCover on: 192.168.88.60
2025-02-04 10:41:29.484 DEBUG (MainThread) [custom_components.acmeda] New AcmedaCover 1100286085403
2025-02-04 10:41:29.486 DEBUG (MainThread) [custom_components.acmeda] Looking for new AcmedaBattery on: 192.168.88.60
2025-02-04 10:41:29.486 DEBUG (MainThread) [custom_components.acmeda] New AcmedaBattery 1100286085403
2025-02-04 10:41:29.635 DEBUG (MainThread) [custom_components.acmeda] Hub scenes updated
2025-02-04 10:41:29.897 DEBUG (MainThread) [custom_components.acmeda] Hub timers updated
2025-02-04 10:41:30.717 DEBUG (SyncWorker_14) [custom_components.acmeda] Device update notification received: Battery
2025-02-04 10:41:30.717 DEBUG (SyncWorker_2) [custom_components.acmeda] Device update notification received: None
`

I think your patch has covered for the TCP Telnet session dropping out, but we might need a patch to catch for the hub rebooting. For now I've just plugged my hub into my UPS and will poke a bit at the code when I have time.

**Comment by andrewD-github** [comment]
Thanks for the info.  when I get some time I will test out that scenario.  The reload should fully unload and reload the integration - so not sure what's happening there
`
async def async_reload_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:

    await async_unload_entry(hass, entry)
    await async_setup_entry(hass, entry)
`

This code does try to reconnect but it only does it 3 times (max_retries=3) with a 5 second wait between (retry_delay=5). 
Perhaps you could bump those up (say 100 retries and a 30 second wait) and test it out?
`

    async def send_payload(self, command, message_type, message, max_retries=3, retry_delay=5):
        """Send payload to the hub with retry logic."""
        if not self.running:
            raise errors.NotRunningException
        await self.handshake.wait()

        data = message_type + utils.pack_int(self.sequence, 2) + message
        checksum = bytes([sum(data) & 0xFF])
        self.sequence += 2
        command_header = const.HEADER + command + bytes.fromhex("05") + self.topic
        length = len(data) + 1  # bytes.fromhex('0C00')
        buffer = command_header + utils.pack_int(length, 2) + data + checksum
        _LOGGER.debug(f"Sending buffer {binascii.hexlify(buffer)}")

        for attempt in range(1, max_retries + 1):
            try:
                self.protocol.send(buffer)
                return  # Successfully sent
            except errors.NotConnectedException as e:
                _LOGGER.warning(f"{self.host}: Connection lost. Retrying... (Attempt {attempt})")
                await asyncio.sleep(retry_delay)
                await self.reconnect()
            except Exception as e:
                _LOGGER.error(f"{self.host}: Unexpected error while sending payload: {e}")
                raise e`

**Comment by gavintweedie** [comment]
As a follow up, it's been a couple of weeks now and no disconnects (or if there was, it recovered itself). @andrewD-github I hope @atmurray may consider accepting your patch.

1. reload functionality
2. better resilience for reconnect when disconnect

**Comment by gavintweedie** [comment]
3 more weeks later, no disconnects even when trying to encourage it (reboot APs etc etc).

**Comment by gavintweedie** [comment]
Semi final follow up to say I've still not had disconnection/stuck disconnection issues and it's been ~6 weeks.

**Comment by atmurray** [comment]
Hi all, sorry for the exceptionally slow response - my day job has been all-consuming.

I think I've worked out what is going wrong here, the hint was the unhandled exception being thrown in the close function:
File "/usr/local/lib/python3.12/site-packages/aiopulse/transport.py", line 161, in send raise NotConnectedException aiopulse.errors.NotConnectedException

The loop in hub.run() is designed to reconnect and deal with connection failures. It catches any exceptions not able to be handled at a payload level and in response tries to reconnect. As part of the reconnect it calls the close function of the transport layer to make sure everything is cleaned up properly and that was throwing a subsequent exception that was not being caught. I've added exception handling in the transport layer and improved the exception handling in the run routine.

I haven't added the retry logic contained in the patch as that shouldn't be necessary as this is all running over a TCP connection.

I've committed this to the develop branch of aiopulse, would appreciate if you guys could apply it and test it out:
https://github.com/atmurray/aiopulse/tree/develop
https://github.com/atmurray/aiopulse/archive/refs/heads/develop.zip

**Comment by atmurray** [comment]
OK I've just committed another little improvement, commands that the hub doesn't respond with an acknowledgement (the hub should send back an empty message immediately) within 3 seconds will be retried up to three times. This should make commands more reliable as I had noticed from time to time that they silently fail.

**Comment by atmurray** [comment]
For those using HACS, I've pre-release v0.4.7:
https://github.com/atmurray/ha-acmeda/releases/tag/v0.4.7

**Comment by gavintweedie** [comment]
@atmurray I've removed @andrewD-github patched version and installed your 0.4.7 from HACS, initial tests are device is working (discovery, up/down etc). I'll report back in a few days if I have any of the previous issues re-appear.

No need to apologise for the delay, super happy you wrote this its really appreciated!

**Comment by atmurray** [comment]
How have you found things? Happy for me to close this out?

**Comment by gavintweedie** [comment]
No issues at all since the update. I think close this out.
